name: DOI Registration Gazette
on:
  workflow_dispatch:
    inputs:
      slug:
        description: 'Slug of blog post'     
        required: true
        default: 'blog-post-slug'

  # Allows external webhook trigger
  repository_dispatch:
    types:
      - publish
#on:
#  workflow_dispatch:
#   schedule: 
#     - cron: '0 16 * * 1-5'
jobs:
  register:
    runs-on: ubuntu-latest
    env:
      CROSSREF_DEPOSITOR_NAME: ${{ secrets.CROSSREF_DEPOSITOR_NAME }}
      CROSSREF_DEPOSITOR_EMAIL: ${{ secrets.CROSSREF_DEPOSITOR_EMAIL }}
      CROSSREF_REGISTRANT: ${{ secrets.CROSSREF_REGISTRANT }}
    steps:
      - uses: actions/checkout@v2          
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install commonmeta-ruby
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Generate XML
        run: |
          mkdir -p upload
          bundle exec commonmeta https://www.syldavia-gazette.org/${{ github.event.inputs.slug }} -t crossref_xml > upload/${{ github.event.inputs.slug }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: uploads
          path: upload/temp        
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: uploads
      - name: curl
        uses: wei/curl@v1
        id: api
        with:
          args: -X POST -F "operation=doMDUpload" -F "login_id=${{ secrets.CROSSREF_USERNAME_WITH_ROLE }}" -F "login_passwd=${{ secrets.CROSSREF_PASSWORD }}" -F "fname=@upload/temp https://doi.crossref.org/servlet/deposit
           